---
# yamllint disable rule:line-length

- name: Deploy PostgreSQL HA Cluster (based on "Patroni" and "{{ dcs_type }}") with DNS Connection Point
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

- name: Gathering facts from all servers
  hosts: all
  gather_facts: true
  tags: always

- import_playbook: etcd_cluster.yml
  when: not dcs_exists|bool and dcs_type == "etcd"
  tags: etcd

- hosts: postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/system.yml

  pre_tasks:
    - name: Set Astra Linux specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"
      when: ansible_os_family is search("Astra Linux")
      tags: always

    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"
      when: not ansible_os_family == 'Rocky' and not ansible_os_family == 'AlmaLinux'
      tags: always

    - name: Include PostgreSQL-specific variables
      include_vars: "vars/postgres/PostgreSQL.yml"
      when: postgresql_fork != 'PostgresPro'

    - name: Include PostgresPro-specific variables
      include_vars: "vars/postgres/PostgresPro.yml"
      when: postgresql_fork == 'PostgresPro'

    - name: Checking Linux distribution
      fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions

    - name: Checking version of OS Linux
      fail:
        msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
      when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian"
      tags: add_repo, install_packages, install_postgres

    - name: Make sure the gnupg and apt-transport-https packages are present
      apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: present
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian"
      tags: add_repo, install_packages, install_postgres

    - name: Build a firewall_ports_dynamic_var
      set_fact:
        firewall_ports_dynamic_var: "{{ firewall_ports_dynamic_var |default([]) }} + {{ firewall_allowed_tcp_ports_for[item] }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

    - name: Build a firewall_rules_dynamic_var
      set_fact:
        firewall_rules_dynamic_var: "{{ firewall_rules_dynamic_var |default([]) }} + {{ firewall_additional_rules_for[item] }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

  roles:
    - role: ansible-role-firewall
      environment: "{{ proxy_env | default({}) }}"
      vars:
        firewall_allowed_tcp_ports: "{{ firewall_ports_dynamic_var|list | unique }}"
        firewall_additional_rules: "{{ firewall_rules_dynamic_var|list | unique }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

    - role: packages
    - role: sudo
    - role: sysctl
    - role: transparent_huge_pages
    - role: pam_limits
    - role: timezone
    - role: dnscp

    - role: watchdog
      when: patroni_with_watchdog|bool

- import_playbook: balancers.yml
  when: with_haproxy_load_balancing|bool
  tags: load_balancing, haproxy

- hosts: postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/system.yml

  pre_tasks:
    - name: Set Astra Linux specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"
      when: ansible_os_family is search("Astra Linux")
      tags: always

    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"
      when: not ansible_os_family == 'Rocky' and not ansible_os_family == 'AlmaLinux'
      tags: always

    - name: Include PostgreSQL-specific variables
      include_vars: "vars/postgres/PostgreSQL.yml"
      when: postgresql_fork != 'PostgresPro'

    - name: Include PostgresPro-specific variables
      include_vars: "vars/postgres/PostgresPro.yml"
      when: postgresql_fork == 'PostgresPro'

  roles:
    - role: patroni

    # finish (info)
    - role: deploy-finish

...
