---
# yamllint disable rule:line-length

# SSL: Obtaining the Private IP Addresses of Managed Nodes
#  https://www.digitalocean.com/community/tutorials/how-to-set-up-and-secure-an-etcd-cluster-with-ansible-on-ubuntu-18-04)
- name: Deploy etcd Cluster | Get etcd private IP
  hosts: etcd_cluster
  become: true
  become_method: sudo
  any_errors_fatal: true

  tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"

    - shell: ip -f inet addr show "{{ patroni_etcd_hosts.ifname }}" | sed -En -e 's/.*inet ([0-9.]+).*/\1/p'
      register: etcd_privateIP

# PKI
- name: Deploy etcd Cluster | Deploy CA if ca.key file non exist
  hosts: localhost
  become: true
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true

  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: "Check CA private key exists"
      stat:
        path: "{{ pki_cert_artifacts_dir }}/ca.key"
      register: pki_ca_key

    - name: "File exist"
      debug:
        msg: "ca.key exist, deploy new Root CA skipping"
      when: pki_ca_key.stat.exists|bool and pki_ca_key.stat.isreg|bool

    - name: "Check CA certificate file exists"
      stat:
        path: "{{ pki_cert_artifacts_dir }}/ca.crt"
      register: pki_ca_cert

    - name: "File not exist"
      debug:
        msg: "ca.crt not exist"
      when: not pki_ca_cert.stat.exists|bool
  roles:
    # Deploy CA if ca.key file non exist
    - role: ca
      when: not pki_ca_key.stat.exists|bool
    - role: install-root-cert # on Ansible host

# SSL: Generating ETCD members’ Private Keys and CSRs
- name: Deploy etcd Cluster | Generating ETCD members’ Private Keys and CSRs
  hosts: localhost
  become: true
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: "Generate private key for each member"
      openssl_privatekey:
        path: "{{ pki_cert_artifacts_dir }}/{{item}}.key"
        type: RSA
        size: 4096
        state: present
        force: true
      with_items: "{{ groups['etcd_cluster'] }}"

    - name: "Generate CSR for each member"
      openssl_csr:
        path: "{{ pki_cert_artifacts_dir }}/{{item}}.csr"
        privatekey_path: "{{ pki_cert_artifacts_dir }}/{{item}}.key"
        common_name: "{{item}}"
        key_usage:
          - digitalSignature
        extended_key_usage:
          - serverAuth
          - clientAuth
        subject_alt_name:
          - DNS:{{item}}
          - IP:{{ hostvars[item]['etcd_privateIP']['stdout']}}
          - IP:127.0.0.1
        force: true
      with_items: "{{ groups['etcd_cluster'] }}"

    - name: "Generate an etcd member certificate signed with our own CA certificate"
      openssl_certificate:
        path: "{{ pki_cert_artifacts_dir }}/{{item}}.crt"
        csr_path: "{{ pki_cert_artifacts_dir }}/{{item}}.csr"
        ownca_path: "{{ pki_cert_artifacts_dir }}/ca.crt"
        ownca_privatekey_path: "{{ pki_cert_artifacts_dir }}/ca.key"
        provider: ownca
        force: true
      with_items: "{{ groups['etcd_cluster'] }}"

# Deploy ETCD
- name: Deploy etcd Cluster | On target hosts
  hosts: etcd_cluster
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  pre_tasks:
    #- name: "Set variable: ansible_python_interpreter"
    #  ansible.builtin.set_fact:
    #    ansible_python_interpreter: "/usr/bin/env python3"
    #  when: "'python3' not in (ansible_python_interpreter | default(''))"
    #  tags: always

    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Include system variables
      ansible.builtin.include_vars: "vars/system.yml"

    - name: Set Astra Linux specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
      when: ansible_os_family is search("Astra Linux")

    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
      when: not ansible_os_family == 'Rocky' and not ansible_os_family == 'AlmaLinux'

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Stop playbook
      ansible.builtin.fail:
        msg: "Fatal: The etcd service is exists! Stopping playbook."
      when: ansible_facts.services['etcd.service'] is defined

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"

    - name: Make sure the gnupg and apt-transport-https packages are present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"

  roles:
    - role: io-scheduler
    - role: sysctl
    - role: timezone
    - role: install-root-cert

    - role: etcd

...
