---

# Install packages from repository
# Debian
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ system_packages }}"
  environment: "{{ proxy_env | default({}) }}"
  when: ansible_os_family == "Debian"
  tags: install_packages

# PostgreSQL prepare for install (for Debian based only)
- block:
    - name: PostgreSQL | ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        state: present
      environment: "{{ proxy_env | default({}) }}"

    - name: PostgreSQL | disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$

    - name: PostgreSQL | disable log rotation with logrotate for postgresql
      file:
        dest: /etc/logrotate.d/postgresql-common
        state: absent
  when: ansible_os_family == "Debian"
  tags: install_postgres

# Install PostgreSQL from repository
# Debian
- name: Install PostgreSQL packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ postgresql_packages }}"
  environment: "{{ proxy_env | default({}) }}"
  when: ansible_os_family == "Debian"
  tags: install_postgres

...
