---
# yamllint disable rule:line-length

#- name: DNS Connection Point | Make sure handlers are flushed immediately
#  meta: flush_handlers

- name: "DNS Connection Point | Make sure the packages are present"
  package:
    name:
      - dnsutils
      - openssl
    state: present
  environment: "{{ proxy_env | default({}) }}"

- name: DNS Connection Point | Create script directory
  file:
    path: "{{ patroni_scripts_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750

- block:
    - name: "DNS Connection Point | Copy script from Ansible host to remote and assign permissions"
      copy:
        src: "dnscp.sh"
        remote_src: false
        dest: "{{ patroni_scripts_dir }}/dnscp.sh"
        owner: postgres
        group: postgres
        mode: 0771
      ignore_errors: false

    - name: "DNS Connection Point | Save computer account password to file"
      shell: "echo '{{ dnscp.vcomppassword }}' > {{ patroni_scripts_dir }}/dnscp.secret"
      register: result
      failed_when: result.rc != 0

    - name: "DNS Connection Point | Change password file ownership, group and permissions"
      file:
        path: "{{ patroni_scripts_dir }}/dnscp.secret"
        owner: postgres
        group: postgres
        mode: '0600'

  when: existing_pgcluster is not defined or not existing_pgcluster|bool
...
